// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import(
"github.com/gogf/gf/v2/frame/g"
)

// Departments is the golang structure of table departments for DAO operations like Where/Data.
type Departments struct {
g.Meta `orm:"table:departments, dto:true"`
    Id interface{} //   
    Name interface{} //   
    CodeDepartment interface{} //   
    City interface{} //   
}