// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import(
"github.com/gogf/gf/v2/frame/g"
)

// Employees is the golang structure of table employees for DAO operations like Where/Data.
type Employees struct {
g.Meta `orm:"table:employees, dto:true"`
    Id interface{} //   
    Name interface{} //   
    Age interface{} //   
    Email interface{} //   
    Phone interface{} //   
}